fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: flake8 .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: mypy --ignore-missing-imports .
        pass_filenames: false
        language: system